apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-server
  # namespace: demo
  labels:
    app: web
spec:
  replicas: 3
  strategy:
    type: RollingUpdate # default is RollingUpdate
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: front-end
          image: basic-node-server:0.0.3
          imagePullPolicy: Never 
          # ^^ For local deploy
          # image: jmsherry/basic-node-server:0.0.19
          # imagePullPolicy: Always 
          # ^^ For remote deploy
          ports:
            - containerPort: 3000
          resources:
            # You must specify requests for CPU to autoscale
            # based on CPU utilization
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              memory: "128Mi"
              cpu: "500m"
      # imagePullSecrets:
      #   - name: regcred
