---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "basic-server-service"
  # namespace: "demo"
  labels:
    app: "web"
spec:
  ports:
  - protocol: "TCP"
    port: 60000
    targetPort: 3000
  selector:
    app: "web"
  type: "LoadBalancer"
  loadBalancerIP: ""
