---
apiVersion: v1
kind: Pod
metadata:
  name: basic-server
  # namespace: demo
  labels:
    app: web
spec:
  containers:
    - name: front-end
      image: basic-node-server:0.0.1
      imagePullPolicy: Never # stops it pulling from remote
      ports:
        - containerPort: 3000
  # imagePullSecrets:
  #   - name: regcred
---

